stages:
  - build
  - test
  - deploy

cache:
  paths:
    - vendor/
    - node_modules/

variables:
  APP_ENV: 'testing'

build:
  stage: build
  image: php:8.1
  script:
    - composer install
    - npm install
    - npm run prod

test:
  stage: test
  image: php:8.1
  script:
    - php artisan migrate --env=testing
    - php artisan db:seed --env=testing
    - vendor/bin/phpunit

deploy:
  stage: deploy
  image: php:8.1
  script:
    - echo "Deploying to production server..."