
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env.docker
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=bookstore
      - DB_USERNAME=root
      - DB_PASSWORD=admin
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bookstore
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    volumes:
      - dbdata:/var/lib/mysql
      - ./apache-custom.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "3307:3306"
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
